name: Pipeline

on:
  push:
    branches:
      - prod

env:
  DEPLOYMENT_NAME: task1  # Add your deployment name here.
  IMAGE: task1

jobs:
  Pipeline:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Static Code Analysis using Linters

      - name: Linters Static Analysis
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_FIND_ALGORITHM: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      - name: Declare docker tag variables
        id: vars
        shell: bash
        run: |
          GIT_HASH=$(git rev-parse --short "${GITHUB_SHA}")
          echo "##[set-output name=docker_tag;]$(echo ${GITHUB_REF##*/}-${GIT_HASH})"

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:${{ steps.vars.outputs.docker_tag }}" .
          docker build --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:latest" .

      # Push the Docker image to GitHub Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:${{ steps.vars.outputs.docker_tag }}"
          docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:latest"

      # Deploy to Google Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy task1 \
          --region europe-west3 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}