name: Pipeline

on:
  push:
    branches:
      - prod

env:
  IMAGE: JavaSpringBootHelloWorldApp
  GITHUB_ACCOUNT: onderhamamcioglu

jobs:
  Pipeline:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Static Code Analysis using Linters
      - name: Linters Static Analysis
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false #change to true if you want all files to be "linted"
          DEFAULT_BRANCH: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          # FILTER_REGEX_EXCLUDE: .*.github/.*

      # Build & Push the Docker image
      - name: Build & Push
        run: |-
          docker login ghcr.io -u onderhamamcioglu -p ${{ secrets.GITHUB_TOKEN }} 
          docker build --tag "ghcr.io/$GITHUBACCOUNT/$IMAGE:${{ steps.vars.outputs.docker_tag }}" .
          docker build --tag "ghcr.io/$GITHUBACCOUNT/$IMAGE:latest" .
          docker push "ghcr.io/$GITHUBACCOUNT/$IMAGE:${{ steps.vars.outputs.docker_tag }}"
          docker push "ghcr.io/$GITHUBACCOUNT/$IMAGE:latest"

      # Deploy to AWS
    

