name: Pipeline

on:
  push:
    branches:
      - prod

env:
  IMAGE: javaspringboothelloworldapp
  GITHUB_USER: onderhamamcioglu

jobs:
  Pipeline:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Static Code Analysis using Linters
      - name: Linters Static Analysis
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false #change to true if you want all files to be "linted"
          DEFAULT_BRANCH: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          # FILTER_REGEX_EXCLUDE: .*.github/.*

      # Build & Push the Docker image
      - name: Build & Push
        run: |-
          docker login ghcr.io -u $GITHUB_USER -p ${{ secrets.GITHUB_TOKEN }} 
          docker build --tag "ghcr.io/$GITHUB_USER/$IMAGE:latest" .
          docker push "ghcr.io/$GITHUB_USER/$IMAGE:latest"

      # Deploy to AWS
      
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.KEY_PAIR }}
          script: |-
            sudo docker login ghcr.io -u $GITHUB_USER -p ${{ secrets.GITHUB_TOKEN }} 
            sudo docker pull ghcr.io/$GITHUB_USER/$IMAGE:latest
            sudo docker run -p8080:8080 $IMAGE:latest
            sudo docker container ls
